# Generated by Django 6.0.6 on 2026-06-20 18:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('key_prefix', models.CharField(max_length=16)),
                ('key_hash', models.CharField(max_length=255, unique=True)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_keys',
                'indexes': [models.Index(fields=['is_active'], name='idx_api_keys_active'), models.Index(fields=['key_prefix'], name='idx_api_keys_prefix'), models.Index(fields=['expires_at'], name='idx_api_keys_expiration')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rate_limit_per_minute__gt', 0)), name='check_rate_limit_gt_0')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('base_url', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'services',
                'indexes': [models.Index(fields=['slug'], name='idx_services_slug'), models.Index(fields=['is_active'], name='idx_services_active')],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path_pattern', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('strip_prefix', models.BooleanField(default=True)),
                ('cache_enabled', models.BooleanField(default=False)),
                ('cache_ttl_seconds', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='gateway.service')),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('method', models.CharField(max_length=10)),
                ('path', models.TextField()),
                ('query_string', models.TextField(blank=True)),
                ('status_code', models.IntegerField()),
                ('latency_ms', models.IntegerField()),
                ('response_size_bytes', models.IntegerField()),
                ('client_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('cache_hit', models.BooleanField(default=False)),
                ('rate_limited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='gateway.apikey')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='gateway.route')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='gateway.service')),
            ],
            options={
                'db_table': 'request_logs',
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['path_pattern'], name='idx_routes_path_pattern'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['method'], name='idx_routes_method'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['service'], name='idx_routes_service'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['is_active'], name='idx_routes_active'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['priority'], name='idx_routes_priority'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['method', 'path_pattern'], name='idx_routes_method_path'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(('cache_ttl_seconds__gte', 0)), name='check_cache_ttl_seconds_gte_0'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['created_at'], name='idx_logs_created_at'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['status_code'], name='idx_logs_status_code'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['route'], name='idx_logs_route'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['service'], name='idx_logs_service'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['api_key'], name='idx_logs_api_key'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['latency_ms'], name='idx_logs_latency'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['cache_hit'], name='idx_logs_cache_hit'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['created_at', 'status_code'], name='idx_logs_created_status'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['created_at', 'service'], name='idx_logs_created_service'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['created_at', 'api_key'], name='idx_logs_created_apikey'),
        ),
    ]
